/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
export {}
declare module 'vue-router/auto-routes' {
  import type { RouteRecordInfo } from 'vue-router'
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/'>
    '/about': RouteRecordInfo<'/about', '/about'>
  }
}
