// Generated by unplugin-auto-import
export {};

declare global {
  const formatApple: typeof import('./formatters/formatApple')['formatApple'];
  const formatBanana: typeof import('./formatters/formatBanana')['formatBanana'];
  const $set: typeof import('./formatters/setValue')['$set'];
}
