// Generated by unplugin-vue-components
export {};

declare module 'vue' {
  export interface GlobalComponents {
    AppleCard: typeof import('./components/AppleCard.vue')['default'];
    BananaCard: typeof import('./components/BananaCard.vue')['default'];
  }
}
