/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppleCard: typeof import('./components/AppleCard.vue')['default']
    BananaCard: typeof import('./components/BananaCard.vue')['default']
  }
}
