packages:
  - packages/*
  - '!packages/knip/fixtures'
allowBuilds:
  esbuild: false
  sharp: false
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - release-it
  - '@release-it/bumper'
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - undici-types@6.21.0
