export { IMPORT_STAR, KNIP_CONFIG_LOCATIONS, SIDE_EFFECTS } from '../constants.js';
export type { DependencyNode, DependencyNodes } from '../graph-explorer/operations/get-dependency-usage.js';
export { finalizeConfigurationHints } from '../reporters/util/configuration-hints.js';
export { getIssuePrefix } from '../reporters/util/util.js';
export type { Results } from '../run.js';
export type { Issue, Issues, IssueType, Rules } from '../types/issues.js';
export type { PackageJson } from '../types/package-json.js';
export { createOptions, type MainOptions } from '../util/create-options.js';
export { buildFileDescriptor, type FileDescriptorOptions } from './file-descriptor.js';
export { buildPackageJsonDescriptor, type PackageJsonFile } from './package-json-descriptor.js';
export { createSession, type Session } from './session.js';
export type { ContentionDetails, Export, File, SourceLocation } from './types.js';
