import assert from 'node:assert/strict';
import test from 'node:test';
import { exec } from '../helpers/exec.ts';
import { resolve } from '../helpers/resolve.ts';

const byFile = (a, b) => a.file.localeCompare(b.file);

const cases = [
  {
    desc: 'exports & types',
    cwd: 'fixtures/exports/basic',
    expected: {
      issues: [
        {
          file: 'default.ts',
          binaries: [],
          catalog: [],
          dependencies: [],
          devDependencies: [],
          duplicates: [],
          enumMembers: [],
          exports: [{ name: 'NamedExport', line: 1, col: 14, pos: 13 }],
          files: [],
          namespaceMembers: [],
          optionalPeerDependencies: [],
          types: [],
          unlisted: [],
          unresolved: [],
        },
        {
          file: 'dynamic-import.ts',
          binaries: [],
          catalog: [],
          dependencies: [],
          devDependencies: [],
          duplicates: [],
          enumMembers: [],
          exports: [{ name: 'unusedZero', line: 3, col: 14, pos: 39 }],
          files: [],
          namespaceMembers: [],
          optionalPeerDependencies: [],
          types: [],
          unlisted: [],
          unresolved: [],
        },
        {
          file: 'my-mix.ts',
          binaries: [],
          catalog: [],
          dependencies: [],
          devDependencies: [],
          duplicates: [],
          enumMembers: [],
          exports: [{ name: 'unusedInMix', line: 1, col: 14, pos: 13 }],
          files: [],
          namespaceMembers: [],
          optionalPeerDependencies: [],
          types: [],
          unlisted: [],
          unresolved: [],
        },
        {
          file: 'my-module.ts',
          binaries: [],
          catalog: [],
          dependencies: [],
          devDependencies: [],
          duplicates: [
            [
              { name: 'exportedResult', line: 26, col: 14, pos: 770 },
              { name: 'default', line: 30, col: 16, pos: 855 },
            ],
          ],
          enumMembers: [],
          exports: [
            { name: 'unusedNumber', line: 23, col: 14, pos: 682 },
            { name: 'unusedFunction', line: 24, col: 14, pos: 713 },
            { name: 'default', line: 30, col: 16, pos: 855 },
          ],
          files: [],
          namespaceMembers: [],
          optionalPeerDependencies: [],
          types: [{ name: 'MyAnyType', line: 28, col: 13, pos: 822 }],
          unlisted: [],
          unresolved: [],
        },
        {
          file: 'my-namespace.ts',
          binaries: [],
          catalog: [],
          dependencies: [],
          devDependencies: [],
          duplicates: [],
          enumMembers: [],
          exports: [{ namespace: 'MyNamespace', name: 'nsUnusedKey', line: 3, col: 14, pos: 84 }],
          files: [],
          namespaceMembers: [],
          optionalPeerDependencies: [],
          types: [{ namespace: 'MyNamespace', name: 'MyNamespace', line: 5, col: 18, pos: 119 }],
          unlisted: [],
          unresolved: [],
        },
        {
          file: 'named-exports.ts',
          binaries: [],
          catalog: [],
          dependencies: [],
          devDependencies: [],
          duplicates: [],
          enumMembers: [],
          exports: [
            { name: 'renamedExport', line: 6, col: 30, pos: 179 },
            { name: 'namedExport', line: 7, col: 15, pos: 215 },
          ],
          files: [],
          namespaceMembers: [],
          optionalPeerDependencies: [],
          types: [],
          unlisted: [],
          unresolved: [],
        },
        {
          file: 'types.ts',
          binaries: [],
          catalog: [],
          dependencies: [],
          devDependencies: [],
          duplicates: [],
          enumMembers: [],
          exports: [],
          files: [],
          namespaceMembers: [],
          optionalPeerDependencies: [],
          types: [
            { name: 'MyEnum', line: 3, col: 13, pos: 71 },
            { name: 'MyType', line: 8, col: 15, pos: 146 },
          ],
          unlisted: [],
          unresolved: [],
        },
      ],
    },
  },
  {
    desc: 'files, unlisted & unresolved',
    cwd: 'fixtures/resolution/module-resolution-non-std',
    expected: {
      issues: [
        {
          file: 'src/unused.ts',
          binaries: [],
          catalog: [],
          dependencies: [],
          devDependencies: [],
          duplicates: [],
          enumMembers: [],
          exports: [],
          files: [{ name: 'src/unused.ts' }],
          namespaceMembers: [],
          optionalPeerDependencies: [],
          types: [],
          unlisted: [],
          unresolved: [],
        },
        {
          file: 'src/index.ts',
          binaries: [],
          catalog: [],
          dependencies: [],
          devDependencies: [],
          duplicates: [],
          enumMembers: [],
          exports: [],
          files: [],
          namespaceMembers: [],
          optionalPeerDependencies: [],
          types: [],
          unlisted: [
            { name: 'unresolved', line: 9, col: 27, pos: 450 },
            { name: '@org/unresolved', line: 10, col: 27, pos: 490 },
          ],
          unresolved: [{ name: './unresolved', line: 8, col: 24, pos: 408 }],
        },
      ],
    },
  },
  {
    desc: 'enum members',
    cwd: 'fixtures/types/enum-members',
    expected: {
      issues: [
        {
          file: 'members.ts',
          binaries: [],
          catalog: [],
          dependencies: [],
          devDependencies: [],
          duplicates: [],
          enumMembers: [
            { namespace: 'MyEnum', name: 'B_Unused', line: 9, col: 3, pos: 127 },
            { namespace: 'MyEnum', name: 'D-Key', line: 11, col: 3, pos: 165 },
          ],
          exports: [],
          files: [],
          namespaceMembers: [],
          optionalPeerDependencies: [],
          types: [],
          unlisted: [],
          unresolved: [],
        },
      ],
    },
  },
  {
    desc: 'dependencies',
    cwd: 'fixtures/dependencies/basic',
    expected: {
      issues: [
        {
          file: 'unused-module.ts',
          binaries: [],
          catalog: [],
          dependencies: [],
          devDependencies: [],
          duplicates: [],
          enumMembers: [],
          exports: [],
          files: [{ name: 'unused-module.ts' }],
          namespaceMembers: [],
          optionalPeerDependencies: [],
          types: [],
          unlisted: [],
          unresolved: [],
        },
        {
          file: 'package.json',
          binaries: [{ name: 'jest' }, { name: 'start-server' }],
          catalog: [],
          dependencies: [
            { name: '@tootallnate/once', line: 8, col: 6, pos: 131 },
            { name: 'fs-extra', line: 10, col: 6, pos: 190 },
          ],
          devDependencies: [{ name: 'mocha', line: 23, col: 6, pos: 422 }],
          duplicates: [],
          enumMembers: [],
          exports: [],
          files: [],
          namespaceMembers: [],
          optionalPeerDependencies: [],
          types: [],
          unlisted: [],
          unresolved: [],
        },
      ],
    },
  },
];

for (const { desc, cwd, expected } of cases) {
  test(`knip --reporter json (${desc})`, () => {
    const result = JSON.parse(exec('knip --reporter json', { cwd: resolve(cwd) }).stdout);
    result.issues.sort(byFile);
    expected.issues.sort(byFile);
    assert.deepEqual(result, expected);
  });
}
