name: 💡 Feature Request (RFC)
description: Suggest an idea for this project
title: '💡 '
labels: ['feature request']
body:
  - type: markdown
    attributes:
      value:
        Use common sense and provide the necessary information to explain why
        the feature is useful to you and to others. Thanks!
  - type: textarea
    id: description
    attributes:
      label: Suggest an idea for this project
    validations:
      required: true
