name: 🧩 Everything Else
description: Discuss anything related to Knip
title: '🧩 '
labels: ['discussion']
body:
  - type: markdown
    attributes:
      value:
        Feel free to discuss anything related to Knip. By the way, there's also
        a [Discord channel](https://discord.gg/r5uXTtbTpc).
  - type: textarea
    id: description
    attributes:
      label: Discuss anything related to Knip
    validations:
      required: true
