import type { IsPluginEnabled, Plugin } from '../../types/config.ts';
import { hasDependency } from '../../util/plugin.ts';
import { findGeneratedDts } from '../_vue/auto-import.ts';

// https://uvr.esm.is — also shipped as `vue-router/vite` since vue-router v4.5

const title = 'unplugin-vue-router';

const enablers = ['unplugin-vue-router', 'vue-router'];

const isEnabled: IsPluginEnabled = ({ cwd, dependencies }) =>
  hasDependency(dependencies, ['unplugin-vue-router']) ||
  (hasDependency(dependencies, ['vue-router']) && findGeneratedDts(cwd, 'Generated by vue-router').length > 0);

const production = ['src/pages/**/*.{vue,md}'];

const plugin: Plugin = {
  title,
  enablers,
  isEnabled,
  production,
};

export default plugin;
