/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const resetCounter: typeof import('./composables/useCounter')['resetCounter']
  const useCard: typeof import('./components/Card')['useCard']
  const useCounter: typeof import('./composables/useCounter')['useCounter']
  const useTheme: typeof import('./composables/useTheme')['useTheme']
  const useUnused: typeof import('./composables/useUnused')['useUnused']
}
