/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DocCard: typeof import('./components/DocCard.vue')['default']
    DocFenced: typeof import('./components/DocFenced.vue')['default']
    DocUnused: typeof import('./components/DocUnused.vue')['default']
  }
}
