// This file is auto-generated by TanStack Router
import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as PostsPostIdRoute } from './routes/posts/$postId';

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/posts/$postId': {
      preLoaderRoute: typeof PostsPostIdRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

export const routeTree = rootRoute.addChildren([IndexRoute, PostsPostIdRoute]);
