/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppCard: typeof import('./components/AppCard.vue')['default']
  }
}
