/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * File format version
 */
type FileVersion = number;
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^(?:@[a-zA-Z0-9_-]+/)?[a-zA-Z0-9_-]+$".
 */
type Project = Project1 & {
  cli?: {
    [k: string]: unknown;
  };
  schematics?: SchematicOptions;
  /**
   * The prefix to apply to generated selectors.
   */
  prefix?: string;
  /**
   * Root of the project files.
   */
  root: string;
  i18n?: I18N;
  /**
   * The root of the source files, assets and index.html file structure.
   */
  sourceRoot?: string;
  /**
   * Project type.
   */
  projectType: 'application' | 'library';
  architect?: {
    [k: string]:
      | {
          /**
           * The builder used for this package.
           */
          builder: string;
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: {
            [k: string]: unknown;
          };
          /**
           * A map of alternative target options.
           */
          configurations?: {
            [k: string]: {
              [k: string]: unknown;
            };
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:app-shell';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: AppShellTarget;
          configurations?: {
            [k: string]: AppShellTarget;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:browser';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: WebpackBrowserSchemaForBuildFacade;
          configurations?: {
            [k: string]: WebpackBrowserSchemaForBuildFacade;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:browser-esbuild';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: EsbuildBrowserSchemaForBuildFacade;
          configurations?: {
            [k: string]: EsbuildBrowserSchemaForBuildFacade;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:dev-server';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: DevServerTarget;
          configurations?: {
            [k: string]: DevServerTarget;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:extract-i18n';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: ExtractI18NTarget;
          configurations?: {
            [k: string]: ExtractI18NTarget;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:karma';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: KarmaTarget;
          configurations?: {
            [k: string]: KarmaTarget;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:jest';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: JestBrowserSchemaForBuildFacade;
          configurations?: {
            [k: string]: JestBrowserSchemaForBuildFacade;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:protractor';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: ProtractorTarget;
          configurations?: {
            [k: string]: ProtractorTarget;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:server';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: UniversalTarget;
          configurations?: {
            [k: string]: UniversalTarget;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:ng-packagr';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: NgPackagrTarget;
          configurations?: {
            [k: string]: NgPackagrTarget;
          };
        };
  };
  targets?: {
    [k: string]:
      | {
          /**
           * The builder used for this package.
           */
          builder: string;
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: {
            [k: string]: unknown;
          };
          /**
           * A map of alternative target options.
           */
          configurations?: {
            [k: string]: {
              [k: string]: unknown;
            };
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:app-shell';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: AppShellTarget;
          configurations?: {
            [k: string]: AppShellTarget;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:browser';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: WebpackBrowserSchemaForBuildFacade;
          configurations?: {
            [k: string]: WebpackBrowserSchemaForBuildFacade;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:browser-esbuild';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: EsbuildBrowserSchemaForBuildFacade;
          configurations?: {
            [k: string]: EsbuildBrowserSchemaForBuildFacade;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:dev-server';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: DevServerTarget;
          configurations?: {
            [k: string]: DevServerTarget;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:extract-i18n';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: ExtractI18NTarget;
          configurations?: {
            [k: string]: ExtractI18NTarget;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:karma';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: KarmaTarget;
          configurations?: {
            [k: string]: KarmaTarget;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:jest';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: JestBrowserSchemaForBuildFacade;
          configurations?: {
            [k: string]: JestBrowserSchemaForBuildFacade;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:protractor';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: ProtractorTarget;
          configurations?: {
            [k: string]: ProtractorTarget;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:server';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: UniversalTarget;
          configurations?: {
            [k: string]: UniversalTarget;
          };
        }
      | {
          builder?: '@angular-devkit/build-angular:ng-packagr';
          /**
           * A default named configuration to use when a target configuration is not provided.
           */
          defaultConfiguration?: string;
          options?: NgPackagrTarget;
          configurations?: {
            [k: string]: NgPackagrTarget;
          };
        };
  };
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^[a-z]{1,3}-.*".
   */
  [k: string]: unknown;
};
type Project1 = {
  [k: string]: unknown;
};

export interface AngularCLIWorkspaceConfiguration {
  $schema?: string;
  version: FileVersion;
  cli?: CliOptions;
  schematics?: SchematicOptions;
  /**
   * Path where new projects will be created.
   */
  newProjectRoot?: string;
  projects?: {
    [k: string]: Project;
  };
}
interface CliOptions {
  /**
   * The list of schematic collections to use.
   */
  schematicCollections?: string[];
  /**
   * Specify which package manager tool to use.
   */
  packageManager?: 'npm' | 'cnpm' | 'yarn' | 'pnpm';
  /**
   * Control CLI specific console warnings
   */
  warnings?: {
    /**
     * Show a warning when the global version is newer than the local one.
     */
    versionMismatch?: boolean;
  };
  /**
   * Share pseudonymous usage data with the Angular Team at Google.
   */
  analytics?: boolean | string;
  /**
   * Control disk cache.
   */
  cache?: {
    /**
     * Configure in which environment disk cache is enabled.
     */
    environment?: 'local' | 'ci' | 'all';
    /**
     * Configure whether disk caching is enabled.
     */
    enabled?: boolean;
    /**
     * Cache base path.
     */
    path?: string;
  };
}
interface SchematicOptions {
  '@schematics/angular:application'?: AngularApplicationOptionsSchema;
  '@schematics/angular:class'?: AngularClassOptionsSchema;
  '@schematics/angular:component'?: AngularComponentOptionsSchema;
  '@schematics/angular:directive'?: AngularDirectiveOptionsSchema;
  '@schematics/angular:enum'?: AngularEnumOptionsSchema;
  '@schematics/angular:guard'?: AngularGuardOptionsSchema;
  '@schematics/angular:interceptor'?: AngularInterceptorOptionsSchema;
  '@schematics/angular:interface'?: AngularInterfaceOptionsSchema;
  '@schematics/angular:library'?: LibraryOptionsSchema;
  '@schematics/angular:pipe'?: AngularPipeOptionsSchema;
  '@schematics/angular:ng-new'?: AngularNgNewOptionsSchema;
  '@schematics/angular:resolver'?: AngularResolverOptionsSchema;
  '@schematics/angular:service'?: AngularServiceOptionsSchema;
  '@schematics/angular:web-worker'?: AngularWebWorkerOptionsSchema;
  [k: string]: unknown;
}
/**
 * Generates a new basic application definition in the "projects" subfolder of the workspace.
 */
interface AngularApplicationOptionsSchema {
  /**
   * The root directory of the new application.
   */
  projectRoot?: string;
  /**
   * The name of the new application.
   */
  name?: string;
  /**
   * Include styles inline in the root component.ts file. Only CSS styles can be included inline. Default is false, meaning that an external styles file is created and referenced in the root component.ts file.
   */
  inlineStyle?: boolean;
  /**
   * Include template inline in the root component.ts file. Default is false, meaning that an external template file is created and referenced in the root component.ts file.
   */
  inlineTemplate?: boolean;
  /**
   * The view encapsulation strategy to use in the new application.
   */
  viewEncapsulation?: 'Emulated' | 'None' | 'ShadowDom';
  /**
   * Create a routing NgModule.
   */
  routing?: boolean;
  /**
   * A prefix to apply to generated selectors.
   */
  prefix?: string;
  /**
   * The file extension or preprocessor to use for style files.
   */
  style?: 'css' | 'scss' | 'sass' | 'less';
  /**
   * Do not create "spec.ts" test files for the application.
   */
  skipTests?: boolean;
  /**
   * Do not add dependencies to the "package.json" file.
   */
  skipPackageJson?: boolean;
  /**
   * Create a bare-bones project without any testing frameworks. (Use for learning purposes only.)
   */
  minimal?: boolean;
  /**
   * Skip installing dependency packages.
   */
  skipInstall?: boolean;
  /**
   * Creates an application with stricter bundle budgets settings.
   */
  strict?: boolean;
  /**
   * Creates an application based upon the standalone API, without NgModules.
   */
  standalone?: boolean;
}
/**
 * Creates a new, generic class definition in the given project.
 */
interface AngularClassOptionsSchema {
  /**
   * The name of the new class.
   */
  name?: string;
  /**
   * The path at which to create the class, relative to the workspace root.
   */
  path?: string;
  /**
   * The name of the project.
   */
  project?: string;
  /**
   * Do not create "spec.ts" test files for the new class.
   */
  skipTests?: boolean;
  /**
   * Adds a developer-defined type to the filename, in the format "name.type.ts".
   */
  type?: string;
}
/**
 * Creates a new, generic component definition in the given project.
 */
interface AngularComponentOptionsSchema {
  /**
   * The path at which to create the component file, relative to the current workspace. Default is a folder with the same name as the component in the project root.
   */
  path?: string;
  /**
   * The name of the project.
   */
  project?: string;
  /**
   * The name of the component.
   */
  name?: string;
  /**
   * Specifies if the style will contain `:host { display: block; }`.
   */
  displayBlock?: boolean;
  /**
   * Include styles inline in the component.ts file. Only CSS styles can be included inline. By default, an external styles file is created and referenced in the component.ts file.
   */
  inlineStyle?: boolean;
  /**
   * Include template inline in the component.ts file. By default, an external template file is created and referenced in the component.ts file.
   */
  inlineTemplate?: boolean;
  /**
   * Whether the generated component is standalone.
   */
  standalone?: boolean;
  /**
   * The view encapsulation strategy to use in the new component.
   */
  viewEncapsulation?: 'Emulated' | 'None' | 'ShadowDom';
  /**
   * The change detection strategy to use in the new component.
   */
  changeDetection?: 'Default' | 'OnPush';
  /**
   * The prefix to apply to the generated component selector.
   */
  prefix?: {
    [k: string]: unknown;
  } & string;
  /**
   * The file extension or preprocessor to use for style files, or 'none' to skip generating the style file.
   */
  style?: 'css' | 'scss' | 'sass' | 'less' | 'none';
  /**
   * Adds a developer-defined type to the filename, in the format "name.type.ts".
   */
  type?: string;
  /**
   * Do not create "spec.ts" test files for the new component.
   */
  skipTests?: boolean;
  /**
   * Create the new files at the top level of the current project.
   */
  flat?: boolean;
  /**
   * Do not import this component into the owning NgModule.
   */
  skipImport?: boolean;
  /**
   * The HTML selector to use for this component.
   */
  selector?: string;
  /**
   * Specifies if the component should have a selector or not.
   */
  skipSelector?: boolean;
  /**
   * The declaring NgModule.
   */
  module?: string;
  /**
   * The declaring NgModule exports this component.
   */
  export?: boolean;
}
/**
 * Creates a new, generic directive definition in the given project.
 */
interface AngularDirectiveOptionsSchema {
  /**
   * The name of the new directive.
   */
  name?: string;
  /**
   * The path at which to create the interface that defines the directive, relative to the workspace root.
   */
  path?: string;
  /**
   * The name of the project.
   */
  project?: string;
  /**
   * A prefix to apply to generated selectors.
   */
  prefix?: {
    [k: string]: unknown;
  } & string;
  /**
   * Do not create "spec.ts" test files for the new class.
   */
  skipTests?: boolean;
  /**
   * Do not import this directive into the owning NgModule.
   */
  skipImport?: boolean;
  /**
   * The HTML selector to use for this directive.
   */
  selector?: string;
  /**
   * Whether the generated directive is standalone.
   */
  standalone?: boolean;
  /**
   * When true (the default), creates the new files at the top level of the current project.
   */
  flat?: boolean;
  /**
   * The declaring NgModule.
   */
  module?: string;
  /**
   * The declaring NgModule exports this directive.
   */
  export?: boolean;
}
/**
 * Generates a new, generic enum definition in the given project.
 */
interface AngularEnumOptionsSchema {
  /**
   * The name of the enum.
   */
  name?: string;
  /**
   * The path at which to create the enum definition, relative to the current workspace.
   */
  path?: string;
  /**
   * The name of the project in which to create the enum. Default is the configured default project for the workspace.
   */
  project?: string;
  /**
   * Adds a developer-defined type to the filename, in the format "name.type.ts".
   */
  type?: string;
}
/**
 * Generates a new, generic route guard definition in the given project.
 */
interface AngularGuardOptionsSchema {
  /**
   * The name of the new route guard.
   */
  name?: string;
  /**
   * Do not create "spec.ts" test files for the new guard.
   */
  skipTests?: boolean;
  /**
   * When true (the default), creates the new files at the top level of the current project.
   */
  flat?: boolean;
  /**
   * The path at which to create the interface that defines the guard, relative to the current workspace.
   */
  path?: string;
  /**
   * The name of the project.
   */
  project?: string;
  /**
   * Specifies whether to generate a guard as a function.
   */
  functional?: boolean;
  /**
   * Specifies which type of guard to create.
   *
   * @minItems 1
   */
  implements?: [
    'CanActivate' | 'CanActivateChild' | 'CanDeactivate' | 'CanMatch',
    ...('CanActivate' | 'CanActivateChild' | 'CanDeactivate' | 'CanMatch')[],
  ];
}
/**
 * Creates a new, generic interceptor definition in the given project.
 */
interface AngularInterceptorOptionsSchema {
  /**
   * The name of the interceptor.
   */
  name?: string;
  /**
   * The path at which to create the interceptor, relative to the workspace root.
   */
  path?: string;
  /**
   * The name of the project.
   */
  project?: string;
  /**
   * When true (the default), creates files at the top level of the project.
   */
  flat?: boolean;
  /**
   * Do not create "spec.ts" test files for the new interceptor.
   */
  skipTests?: boolean;
  /**
   * Creates the interceptor as a `HttpInterceptorFn`.
   */
  functional?: boolean;
}
/**
 * Creates a new, generic interface definition in the given project.
 */
interface AngularInterfaceOptionsSchema {
  /**
   * The name of the interface.
   */
  name?: string;
  /**
   * The path at which to create the interface, relative to the workspace root.
   */
  path?: string;
  /**
   * The name of the project.
   */
  project?: string;
  /**
   * A prefix to apply to generated selectors.
   */
  prefix?: string;
  /**
   * Adds a developer-defined type to the filename, in the format "name.type.ts".
   */
  type?: string;
}
/**
 * Creates a new, generic library project in the current workspace.
 */
interface LibraryOptionsSchema {
  /**
   * The name of the library.
   */
  name?: string;
  /**
   * The path at which to create the library's public API file, relative to the workspace root.
   */
  entryFile?: string;
  /**
   * A prefix to apply to generated selectors.
   */
  prefix?: string;
  /**
   * Do not add dependencies to the "package.json" file.
   */
  skipPackageJson?: boolean;
  /**
   * Do not install dependency packages.
   */
  skipInstall?: boolean;
  /**
   * Do not update "tsconfig.json" to add a path mapping for the new library. The path mapping is needed to use the library in an app, but can be disabled here to simplify development.
   */
  skipTsConfig?: boolean;
  /**
   * The root directory of the new library.
   */
  projectRoot?: string;
  /**
   * Creates a library based upon the standalone API, without NgModules.
   */
  standalone?: boolean;
}
/**
 * Creates a new, generic pipe definition in the given project.
 */
interface AngularPipeOptionsSchema {
  /**
   * The name of the pipe.
   */
  name?: string;
  /**
   * The path at which to create the pipe, relative to the workspace root.
   */
  path?: string;
  /**
   * The name of the project.
   */
  project?: string;
  /**
   * When true (the default) creates files at the top level of the project.
   */
  flat?: boolean;
  /**
   * Do not create "spec.ts" test files for the new pipe.
   */
  skipTests?: boolean;
  /**
   * Do not import this pipe into the owning NgModule.
   */
  skipImport?: boolean;
  /**
   * Whether the generated pipe is standalone.
   */
  standalone?: boolean;
  /**
   * The declaring NgModule.
   */
  module?: string;
  /**
   * The declaring NgModule exports this pipe.
   */
  export?: boolean;
}
/**
 * Creates a new project by combining the workspace and application schematics.
 */
interface AngularNgNewOptionsSchema {
  /**
   * The directory name to create the workspace in.
   */
  directory?: string;
  /**
   * The name of the new workspace and initial project.
   */
  name?: string;
  /**
   * Do not install dependency packages.
   */
  skipInstall?: boolean;
  /**
   * Link the CLI to the global version (internal development only).
   */
  linkCli?: boolean;
  /**
   * Do not initialize a git repository.
   */
  skipGit?: boolean;
  /**
   * Initial git repository commit information.
   */
  commit?:
    | boolean
    | {
        name?: string;
        email?: string;
        message?: string;
        [k: string]: unknown;
      };
  /**
   * The path where new projects will be created, relative to the new workspace root.
   */
  newProjectRoot?: string;
  /**
   * Include styles inline in the component TS file. By default, an external styles file is created and referenced in the component TypeScript file.
   */
  inlineStyle?: boolean;
  /**
   * Include template inline in the component TS file. By default, an external template file is created and referenced in the component TypeScript file.
   */
  inlineTemplate?: boolean;
  /**
   * The view encapsulation strategy to use in the initial project.
   */
  viewEncapsulation?: 'Emulated' | 'None' | 'ShadowDom';
  /**
   * The version of the Angular CLI to use.
   */
  version?: string;
  /**
   * Generate a routing module for the initial project.
   */
  routing?: boolean;
  /**
   * The prefix to apply to generated selectors for the initial project.
   */
  prefix?: string;
  /**
   * The file extension or preprocessor to use for style files.
   */
  style?: 'css' | 'scss' | 'sass' | 'less';
  /**
   * Do not generate "spec.ts" test files for the new project.
   */
  skipTests?: boolean;
  /**
   * Create a new initial application project in the 'src' folder of the new workspace. When false, creates an empty workspace with no initial application. You can then use the generate application command so that all applications are created in the projects folder.
   */
  createApplication?: boolean;
  /**
   * Create a workspace without any testing frameworks. (Use for learning purposes only.)
   */
  minimal?: boolean;
  /**
   * Creates a workspace with stricter type checking and stricter bundle budgets settings. This setting helps improve maintainability and catch bugs ahead of time. For more information, see https://angular.io/guide/strict-mode
   */
  strict?: boolean;
  /**
   * The package manager used to install dependencies.
   */
  packageManager?: 'npm' | 'yarn' | 'pnpm' | 'cnpm';
  /**
   * Creates an application based upon the standalone API, without NgModules.
   */
  standalone?: boolean;
}
/**
 * Generates a new, generic resolver definition in the given project.
 */
interface AngularResolverOptionsSchema {
  /**
   * The name of the new resolver.
   */
  name?: string;
  /**
   * Do not create "spec.ts" test files for the new resolver.
   */
  skipTests?: boolean;
  /**
   * When true (the default), creates the new files at the top level of the current project.
   */
  flat?: boolean;
  /**
   * Creates the resolver as a `ResolveFn`.
   */
  functional?: boolean;
  /**
   * The path at which to create the interface that defines the resolver, relative to the current workspace.
   */
  path?: string;
  /**
   * The name of the project.
   */
  project?: string;
}
/**
 * Creates a new, generic service definition in the given project.
 */
interface AngularServiceOptionsSchema {
  /**
   * The name of the service.
   */
  name?: string;
  /**
   * The path at which to create the service, relative to the workspace root.
   */
  path?: string;
  /**
   * The name of the project.
   */
  project?: string;
  /**
   * When true (the default), creates files at the top level of the project.
   */
  flat?: boolean;
  /**
   * Do not create "spec.ts" test files for the new service.
   */
  skipTests?: boolean;
}
/**
 * Creates a new, generic web worker definition in the given project.
 */
interface AngularWebWorkerOptionsSchema {
  /**
   * The path at which to create the worker file, relative to the current workspace.
   */
  path?: string;
  /**
   * The name of the project.
   */
  project?: string;
  /**
   * The name of the worker.
   */
  name?: string;
  /**
   * Add a worker creation snippet in a sibling file of the same name.
   */
  snippet?: boolean;
}
/**
 * Project i18n options
 */
interface I18N {
  sourceLocale?:
    | string
    | {
        /**
         * Specifies the locale code of the source locale
         */
        code?: string;
        /**
         * HTML base HREF to use for the locale (defaults to the locale code)
         */
        baseHref?: string;
      };
  locales?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z]{2,3}(-[a-zA-Z]{4})?(-([a-zA-Z]{2}|[0-9]{3}))?(-[a-zA-Z]{5,8})?(-x(-[a-zA-Z0-9]{1,8})+)?$".
     */
    [k: string]:
      | string
      | string[]
      | {
          translation?: string | string[];
          /**
           * HTML base HREF to use for the locale (defaults to the locale code)
           */
          baseHref?: string;
        };
  };
}
/**
 * App Shell target options for Build Facade.
 */
interface AppShellTarget {
  /**
   * A browser builder target use for rendering the application shell in the format of `project:target[:configuration]`. You can also pass in more than one configuration name as a comma-separated list. Example: `project:target:production,staging`.
   */
  browserTarget?: string;
  /**
   * A server builder target use for rendering the application shell in the format of `project:target[:configuration]`. You can also pass in more than one configuration name as a comma-separated list. Example: `project:target:production,staging`.
   */
  serverTarget?: string;
  /**
   * Script that exports the Server AppModule to render. This should be the main JavaScript outputted by the server target. By default we will resolve the outputPath of the serverTarget and find a bundle named 'main' in it (whether or not there's a hash tag).
   */
  appModuleBundle?: string;
  /**
   * The route to render.
   */
  route?: string;
  /**
   * The input path for the index.html file. By default uses the output index.html of the browser target.
   */
  inputIndexPath?: string;
  /**
   * The output path of the index.html file. By default will overwrite the input file.
   */
  outputIndexPath?: string;
}
/**
 * Browser target options
 */
interface WebpackBrowserSchemaForBuildFacade {
  /**
   * List of static application assets.
   */
  assets?: (
    | {
        /**
         * Allow glob patterns to follow symlink directories. This allows subdirectories of the symlink to be searched.
         */
        followSymlinks?: boolean;
        /**
         * The pattern to match.
         */
        glob?: string;
        /**
         * The input directory path in which to apply 'glob'. Defaults to the project root.
         */
        input?: string;
        /**
         * An array of globs to ignore.
         */
        ignore?: string[];
        /**
         * Absolute path within the output.
         */
        output?: string;
      }
    | string
  )[];
  /**
   * The full path for the main entry point to the app, relative to the current workspace.
   */
  main?: string;
  /**
   * Polyfills to be included in the build.
   */
  polyfills?: string[] | string;
  /**
   * The full path for the TypeScript configuration file, relative to the current workspace.
   */
  tsConfig?: string;
  /**
   * Global scripts to be included in the build.
   */
  scripts?: (
    | {
        /**
         * The file to include.
         */
        input?: string;
        /**
         * The bundle name for this extra entry point.
         */
        bundleName?: string;
        /**
         * If the bundle will be referenced in the HTML file.
         */
        inject?: boolean;
      }
    | string
  )[];
  /**
   * Global styles to be included in the build.
   */
  styles?: (
    | {
        /**
         * The file to include.
         */
        input?: string;
        /**
         * The bundle name for this extra entry point.
         */
        bundleName?: string;
        /**
         * If the bundle will be referenced in the HTML file.
         */
        inject?: boolean;
      }
    | string
  )[];
  /**
   * The stylesheet language to use for the application's inline component styles.
   */
  inlineStyleLanguage?: 'css' | 'less' | 'sass' | 'scss';
  /**
   * Options to pass to style preprocessors.
   */
  stylePreprocessorOptions?: {
    /**
     * Paths to include. Paths will be resolved to workspace root.
     */
    includePaths?: string[];
  };
  /**
   * Enables optimization of the build output. Including minification of scripts and styles, tree-shaking, dead-code elimination, inlining of critical CSS and fonts inlining. For more information, see https://angular.io/guide/workspace-config#optimization-configuration.
   */
  optimization?:
    | {
        /**
         * Enables optimization of the scripts output.
         */
        scripts?: boolean;
        /**
         * Enables optimization of the styles output.
         */
        styles?:
          | {
              /**
               * Minify CSS definitions by removing extraneous whitespace and comments, merging identifiers and minimizing values.
               */
              minify?: boolean;
              /**
               * Extract and inline critical CSS definitions to improve first paint time.
               */
              inlineCritical?: boolean;
            }
          | boolean;
        /**
         * Enables optimization for fonts. This option requires internet access. `HTTPS_PROXY` environment variable can be used to specify a proxy server.
         */
        fonts?:
          | {
              /**
               * Reduce render blocking requests by inlining external Google Fonts and Adobe Fonts CSS definitions in the application's HTML index file. This option requires internet access. `HTTPS_PROXY` environment variable can be used to specify a proxy server.
               */
              inline?: boolean;
            }
          | boolean;
      }
    | boolean;
  /**
   * Replace compilation source files with other compilation source files in the build.
   */
  fileReplacements?: (
    | {
        src?: string;
        replaceWith?: string;
      }
    | {
        replace?: string;
        with?: string;
      }
  )[];
  /**
   * The full path for the new output directory, relative to the current workspace.
   * By default, writes output to a folder named dist/ in the current project.
   */
  outputPath?: string;
  /**
   * The path where style resources will be placed, relative to outputPath.
   */
  resourcesOutputPath?: string;
  /**
   * Build using Ahead of Time compilation.
   */
  aot?: boolean;
  /**
   * Output source maps for scripts and styles. For more information, see https://angular.io/guide/workspace-config#source-map-configuration.
   */
  sourceMap?:
    | {
        /**
         * Output source maps for all scripts.
         */
        scripts?: boolean;
        /**
         * Output source maps for all styles.
         */
        styles?: boolean;
        /**
         * Output source maps used for error reporting tools.
         */
        hidden?: boolean;
        /**
         * Resolve vendor packages source maps.
         */
        vendor?: boolean;
      }
    | boolean;
  /**
   * Generate a seperate bundle containing only vendor libraries. This option should only be used for development to reduce the incremental compilation time.
   */
  vendorChunk?: boolean;
  /**
   * Generate a seperate bundle containing code used across multiple bundles.
   */
  commonChunk?: boolean;
  /**
   * Base url for the application being built.
   */
  baseHref?: string;
  /**
   * URL where files will be deployed.
   */
  deployUrl?: string;
  /**
   * Adds more details to output logging.
   */
  verbose?: boolean;
  /**
   * Log progress to the console while building.
   */
  progress?: boolean;
  /**
   * How to handle missing translations for i18n.
   */
  i18nMissingTranslation?: 'warning' | 'error' | 'ignore';
  /**
   * How to handle duplicate translations for i18n.
   */
  i18nDuplicateTranslation?: 'warning' | 'error' | 'ignore';
  /**
   * Translate the bundles in one or more locales.
   */
  localize?: boolean | [string, ...string[]];
  /**
   * Run build when files change.
   */
  watch?: boolean;
  /**
   * Define the output filename cache-busting hashing mode.
   */
  outputHashing?: 'none' | 'all' | 'media' | 'bundles';
  /**
   * Enable and define the file watching poll time period in milliseconds.
   */
  poll?: number;
  /**
   * Delete the output path before building.
   */
  deleteOutputPath?: boolean;
  /**
   * Do not use the real path when resolving modules. If unset then will default to `true` if NodeJS option --preserve-symlinks is set.
   */
  preserveSymlinks?: boolean;
  /**
   * Extract all licenses in a separate file.
   */
  extractLicenses?: boolean;
  /**
   * Enables advanced build optimizations when using the 'aot' option.
   */
  buildOptimizer?: boolean;
  /**
   * Use file name for lazy loaded chunks.
   */
  namedChunks?: boolean;
  /**
   * Enables the use of subresource integrity validation.
   */
  subresourceIntegrity?: boolean;
  /**
   * Generates a service worker config for production builds.
   */
  serviceWorker?: boolean;
  /**
   * Path to ngsw-config.json.
   */
  ngswConfigPath?: string;
  /**
   * Configures the generation of the application's HTML index.
   */
  index?:
    | string
    | {
        /**
         * The path of a file to use for the application's generated HTML index.
         */
        input?: string;
        /**
         * The output path of the application's generated HTML index file. The full provided path will be used and will be considered relative to the application's configured output path.
         */
        output?: string;
        [k: string]: unknown;
      };
  /**
   * Generates a 'stats.json' file which can be analyzed using tools such as 'webpack-bundle-analyzer'.
   */
  statsJson?: boolean;
  /**
   * Budget thresholds to ensure parts of your application stay within boundaries which you set.
   */
  budgets?: Budget[];
  /**
   * TypeScript configuration for Web Worker modules.
   */
  webWorkerTsConfig?: string;
  /**
   * Define the crossorigin attribute setting of elements that provide CORS support.
   */
  crossOrigin?: 'none' | 'anonymous' | 'use-credentials';
  /**
   * A list of CommonJS packages that are allowed to be used without a build time warning.
   */
  allowedCommonJsDependencies?: string[];
}
interface Budget {
  /**
   * The type of budget.
   */
  type?: 'all' | 'allScript' | 'any' | 'anyScript' | 'anyComponentStyle' | 'bundle' | 'initial';
  /**
   * The name of the bundle.
   */
  name?: string;
  /**
   * The baseline size for comparison.
   */
  baseline?: string;
  /**
   * The maximum threshold for warning relative to the baseline.
   */
  maximumWarning?: string;
  /**
   * The maximum threshold for error relative to the baseline.
   */
  maximumError?: string;
  /**
   * The minimum threshold for warning relative to the baseline.
   */
  minimumWarning?: string;
  /**
   * The minimum threshold for error relative to the baseline.
   */
  minimumError?: string;
  /**
   * The threshold for warning relative to the baseline (min & max).
   */
  warning?: string;
  /**
   * The threshold for error relative to the baseline (min & max).
   */
  error?: string;
}
/**
 * Browser target options
 */
interface EsbuildBrowserSchemaForBuildFacade {
  /**
   * List of static application assets.
   */
  assets?: (
    | {
        /**
         * Allow glob patterns to follow symlink directories. This allows subdirectories of the symlink to be searched.
         */
        followSymlinks?: boolean;
        /**
         * The pattern to match.
         */
        glob?: string;
        /**
         * The input directory path in which to apply 'glob'. Defaults to the project root.
         */
        input?: string;
        /**
         * An array of globs to ignore.
         */
        ignore?: string[];
        /**
         * Absolute path within the output.
         */
        output?: string;
      }
    | string
  )[];
  /**
   * The full path for the main entry point to the app, relative to the current workspace.
   */
  main?: string;
  /**
   * Polyfills to be included in the build.
   */
  polyfills?: string[] | string;
  /**
   * The full path for the TypeScript configuration file, relative to the current workspace.
   */
  tsConfig?: string;
  /**
   * Global scripts to be included in the build.
   */
  scripts?: (
    | {
        /**
         * The file to include.
         */
        input?: string;
        /**
         * The bundle name for this extra entry point.
         */
        bundleName?: string;
        /**
         * If the bundle will be referenced in the HTML file.
         */
        inject?: boolean;
      }
    | string
  )[];
  /**
   * Global styles to be included in the build.
   */
  styles?: (
    | {
        /**
         * The file to include.
         */
        input?: string;
        /**
         * The bundle name for this extra entry point.
         */
        bundleName?: string;
        /**
         * If the bundle will be referenced in the HTML file.
         */
        inject?: boolean;
      }
    | string
  )[];
  /**
   * The stylesheet language to use for the application's inline component styles.
   */
  inlineStyleLanguage?: 'css' | 'less' | 'sass' | 'scss';
  /**
   * Options to pass to style preprocessors.
   */
  stylePreprocessorOptions?: {
    /**
     * Paths to include. Paths will be resolved to workspace root.
     */
    includePaths?: string[];
  };
  /**
   * Exclude the listed external dependencies from being bundled into the bundle. Instead, the created bundle relies on these dependencies to be available during runtime.
   */
  externalDependencies?: string[];
  /**
   * Enables optimization of the build output. Including minification of scripts and styles, tree-shaking, dead-code elimination, inlining of critical CSS and fonts inlining. For more information, see https://angular.io/guide/workspace-config#optimization-configuration.
   */
  optimization?:
    | {
        /**
         * Enables optimization of the scripts output.
         */
        scripts?: boolean;
        /**
         * Enables optimization of the styles output.
         */
        styles?:
          | {
              /**
               * Minify CSS definitions by removing extraneous whitespace and comments, merging identifiers and minimizing values.
               */
              minify?: boolean;
              /**
               * Extract and inline critical CSS definitions to improve first paint time.
               */
              inlineCritical?: boolean;
            }
          | boolean;
        /**
         * Enables optimization for fonts. This option requires internet access. `HTTPS_PROXY` environment variable can be used to specify a proxy server.
         */
        fonts?:
          | {
              /**
               * Reduce render blocking requests by inlining external Google Fonts and Adobe Fonts CSS definitions in the application's HTML index file. This option requires internet access. `HTTPS_PROXY` environment variable can be used to specify a proxy server.
               */
              inline?: boolean;
            }
          | boolean;
      }
    | boolean;
  /**
   * Replace compilation source files with other compilation source files in the build.
   */
  fileReplacements?: FileReplacement[];
  /**
   * The full path for the new output directory, relative to the current workspace.
   * By default, writes output to a folder named dist/ in the current project.
   */
  outputPath?: string;
  /**
   * The path where style resources will be placed, relative to outputPath.
   */
  resourcesOutputPath?: string;
  /**
   * Build using Ahead of Time compilation.
   */
  aot?: boolean;
  /**
   * Output source maps for scripts and styles. For more information, see https://angular.io/guide/workspace-config#source-map-configuration.
   */
  sourceMap?:
    | {
        /**
         * Output source maps for all scripts.
         */
        scripts?: boolean;
        /**
         * Output source maps for all styles.
         */
        styles?: boolean;
        /**
         * Output source maps used for error reporting tools.
         */
        hidden?: boolean;
        /**
         * Resolve vendor packages source maps.
         */
        vendor?: boolean;
      }
    | boolean;
  /**
   * Generate a seperate bundle containing only vendor libraries. This option should only be used for development to reduce the incremental compilation time.
   */
  vendorChunk?: boolean;
  /**
   * Generate a seperate bundle containing code used across multiple bundles.
   */
  commonChunk?: boolean;
  /**
   * Base url for the application being built.
   */
  baseHref?: string;
  /**
   * URL where files will be deployed.
   */
  deployUrl?: string;
  /**
   * Adds more details to output logging.
   */
  verbose?: boolean;
  /**
   * Log progress to the console while building.
   */
  progress?: boolean;
  /**
   * How to handle missing translations for i18n.
   */
  i18nMissingTranslation?: 'warning' | 'error' | 'ignore';
  /**
   * How to handle duplicate translations for i18n.
   */
  i18nDuplicateTranslation?: 'warning' | 'error' | 'ignore';
  /**
   * Translate the bundles in one or more locales.
   */
  localize?: boolean | [string, ...string[]];
  /**
   * Run build when files change.
   */
  watch?: boolean;
  /**
   * Define the output filename cache-busting hashing mode.
   */
  outputHashing?: 'none' | 'all' | 'media' | 'bundles';
  /**
   * Enable and define the file watching poll time period in milliseconds.
   */
  poll?: number;
  /**
   * Delete the output path before building.
   */
  deleteOutputPath?: boolean;
  /**
   * Do not use the real path when resolving modules. If unset then will default to `true` if NodeJS option --preserve-symlinks is set.
   */
  preserveSymlinks?: boolean;
  /**
   * Extract all licenses in a separate file.
   */
  extractLicenses?: boolean;
  /**
   * Enables advanced build optimizations when using the 'aot' option.
   */
  buildOptimizer?: boolean;
  /**
   * Use file name for lazy loaded chunks.
   */
  namedChunks?: boolean;
  /**
   * Enables the use of subresource integrity validation.
   */
  subresourceIntegrity?: boolean;
  /**
   * Generates a service worker config for production builds.
   */
  serviceWorker?: boolean;
  /**
   * Path to ngsw-config.json.
   */
  ngswConfigPath?: string;
  /**
   * Configures the generation of the application's HTML index.
   */
  index?:
    | string
    | {
        /**
         * The path of a file to use for the application's generated HTML index.
         */
        input?: string;
        /**
         * The output path of the application's generated HTML index file. The full provided path will be used and will be considered relative to the application's configured output path.
         */
        output?: string;
        [k: string]: unknown;
      }
    | false;
  /**
   * Generates a 'stats.json' file which can be analyzed using tools such as 'webpack-bundle-analyzer'.
   */
  statsJson?: boolean;
  /**
   * Budget thresholds to ensure parts of your application stay within boundaries which you set.
   */
  budgets?: Budget1[];
  /**
   * TypeScript configuration for Web Worker modules.
   */
  webWorkerTsConfig?: string;
  /**
   * Define the crossorigin attribute setting of elements that provide CORS support.
   */
  crossOrigin?: 'none' | 'anonymous' | 'use-credentials';
  /**
   * A list of CommonJS packages that are allowed to be used without a build time warning.
   */
  allowedCommonJsDependencies?: string[];
}
interface FileReplacement {
  replace?: string;
  with?: string;
}
interface Budget1 {
  /**
   * The type of budget.
   */
  type?: 'all' | 'allScript' | 'any' | 'anyScript' | 'anyComponentStyle' | 'bundle' | 'initial';
  /**
   * The name of the bundle.
   */
  name?: string;
  /**
   * The baseline size for comparison.
   */
  baseline?: string;
  /**
   * The maximum threshold for warning relative to the baseline.
   */
  maximumWarning?: string;
  /**
   * The maximum threshold for error relative to the baseline.
   */
  maximumError?: string;
  /**
   * The minimum threshold for warning relative to the baseline.
   */
  minimumWarning?: string;
  /**
   * The minimum threshold for error relative to the baseline.
   */
  minimumError?: string;
  /**
   * The threshold for warning relative to the baseline (min & max).
   */
  warning?: string;
  /**
   * The threshold for error relative to the baseline (min & max).
   */
  error?: string;
}
/**
 * Dev Server target options for Build Facade.
 */
interface DevServerTarget {
  /**
   * A browser builder target to serve in the format of `project:target[:configuration]`. You can also pass in more than one configuration name as a comma-separated list. Example: `project:target:production,staging`.
   */
  browserTarget?: string;
  /**
   * Port to listen on.
   */
  port?: number;
  /**
   * Host to listen on.
   */
  host?: string;
  /**
   * Proxy configuration file. For more information, see https://angular.io/guide/build#proxying-to-a-backend-server.
   */
  proxyConfig?: string;
  /**
   * Serve using HTTPS.
   */
  ssl?: boolean;
  /**
   * SSL key to use for serving HTTPS.
   */
  sslKey?: string;
  /**
   * SSL certificate to use for serving HTTPS.
   */
  sslCert?: string;
  /**
   * Custom HTTP headers to be added to all responses.
   */
  headers?: {
    [k: string]: string;
  };
  /**
   * Opens the url in default browser.
   */
  open?: boolean;
  /**
   * Adds more details to output logging.
   */
  verbose?: boolean;
  /**
   * Whether to reload the page on change, using live-reload.
   */
  liveReload?: boolean;
  /**
   * The URL that the browser client (or live-reload client, if enabled) should use to connect to the development server. Use for a complex dev server setup, such as one with reverse proxies.
   */
  publicHost?: string;
  /**
   * List of hosts that are allowed to access the dev server.
   */
  allowedHosts?: string[];
  /**
   * The pathname where the application will be served.
   */
  servePath?: string;
  /**
   * Don't verify connected clients are part of allowed hosts.
   */
  disableHostCheck?: boolean;
  /**
   * Enable hot module replacement.
   */
  hmr?: boolean;
  /**
   * Rebuild on change.
   */
  watch?: boolean;
  /**
   * Enable and define the file watching poll time period in milliseconds.
   */
  poll?: number;
}
/**
 * Extract i18n target options for Build Facade.
 */
interface ExtractI18NTarget {
  /**
   * A browser builder target to extract i18n messages in the format of `project:target[:configuration]`. You can also pass in more than one configuration name as a comma-separated list. Example: `project:target:production,staging`.
   */
  browserTarget?: string;
  /**
   * Output format for the generated file.
   */
  format?: 'xmb' | 'xlf' | 'xlif' | 'xliff' | 'xlf2' | 'xliff2' | 'json' | 'arb' | 'legacy-migrate';
  /**
   * Log progress to the console.
   */
  progress?: boolean;
  /**
   * Path where output will be placed.
   */
  outputPath?: string;
  /**
   * Name of the file to output.
   */
  outFile?: string;
}
/**
 * Karma target options for Build Facade.
 */
interface KarmaTarget {
  /**
   * The name of the main entry-point file.
   */
  main?: string;
  /**
   * The name of the TypeScript configuration file.
   */
  tsConfig?: string;
  /**
   * The name of the Karma configuration file.
   */
  karmaConfig?: string;
  /**
   * Polyfills to be included in the build.
   */
  polyfills?: string[] | string;
  /**
   * List of static application assets.
   */
  assets?: (
    | {
        /**
         * The pattern to match.
         */
        glob?: string;
        /**
         * The input directory path in which to apply 'glob'. Defaults to the project root.
         */
        input?: string;
        /**
         * Absolute path within the output.
         */
        output?: string;
        /**
         * An array of globs to ignore.
         */
        ignore?: string[];
      }
    | string
  )[];
  /**
   * Global scripts to be included in the build.
   */
  scripts?: (
    | {
        /**
         * The file to include.
         */
        input?: string;
        /**
         * The bundle name for this extra entry point.
         */
        bundleName?: string;
        /**
         * If the bundle will be referenced in the HTML file.
         */
        inject?: boolean;
      }
    | string
  )[];
  /**
   * Global styles to be included in the build.
   */
  styles?: (
    | {
        /**
         * The file to include.
         */
        input?: string;
        /**
         * The bundle name for this extra entry point.
         */
        bundleName?: string;
        /**
         * If the bundle will be referenced in the HTML file.
         */
        inject?: boolean;
      }
    | string
  )[];
  /**
   * The stylesheet language to use for the application's inline component styles.
   */
  inlineStyleLanguage?: 'css' | 'less' | 'sass' | 'scss';
  /**
   * Options to pass to style preprocessors
   */
  stylePreprocessorOptions?: {
    /**
     * Paths to include. Paths will be resolved to workspace root.
     */
    includePaths?: string[];
  };
  /**
   * Globs of files to include, relative to project root.
   * There are 2 special cases:
   *  - when a path to directory is provided, all spec files ending ".spec.@(ts|tsx)" will be included
   *  - when a path to a file is provided, and a matching spec file exists it will be included instead.
   */
  include?: string[];
  /**
   * Globs of files to exclude, relative to the project root.
   */
  exclude?: string[];
  /**
   * Output source maps for scripts and styles. For more information, see https://angular.io/guide/workspace-config#source-map-configuration.
   */
  sourceMap?:
    | {
        /**
         * Output source maps for all scripts.
         */
        scripts?: boolean;
        /**
         * Output source maps for all styles.
         */
        styles?: boolean;
        /**
         * Resolve vendor packages source maps.
         */
        vendor?: boolean;
      }
    | boolean;
  /**
   * Log progress to the console while building.
   */
  progress?: boolean;
  /**
   * Run build when files change.
   */
  watch?: boolean;
  /**
   * Enable and define the file watching poll time period in milliseconds.
   */
  poll?: number;
  /**
   * Do not use the real path when resolving modules. If unset then will default to `true` if NodeJS option --preserve-symlinks is set.
   */
  preserveSymlinks?: boolean;
  /**
   * Override which browsers tests are run against.
   */
  browsers?: string;
  /**
   * Output a code coverage report.
   */
  codeCoverage?: boolean;
  /**
   * Globs to exclude from code coverage.
   */
  codeCoverageExclude?: string[];
  /**
   * Replace compilation source files with other compilation source files in the build.
   */
  fileReplacements?: (
    | {
        src?: string;
        replaceWith?: string;
      }
    | {
        replace?: string;
        with?: string;
      }
  )[];
  /**
   * Karma reporters to use. Directly passed to the karma runner.
   */
  reporters?: string[];
  /**
   * TypeScript configuration for Web Worker modules.
   */
  webWorkerTsConfig?: string;
}
/**
 * Jest target options
 */
interface JestBrowserSchemaForBuildFacade {
  /**
   * Globs of files to include, relative to project root.
   */
  include?: string[];
  /**
   * Globs of files to exclude, relative to the project root.
   */
  exclude?: string[];
  /**
   * The name of the TypeScript configuration file.
   */
  tsConfig?: string;
  /**
   * Polyfills to be included in the build.
   */
  polyfills?: string[] | string;
}
/**
 * Protractor target options for Build Facade.
 */
interface ProtractorTarget {
  /**
   * The name of the Protractor configuration file.
   */
  protractorConfig?: string;
  /**
   * A dev-server builder target to run tests against in the format of `project:target[:configuration]`. You can also pass in more than one configuration name as a comma-separated list. Example: `project:target:production,staging`.
   */
  devServerTarget?: string;
  /**
   * Execute specs whose names match the pattern, which is internally compiled to a RegExp.
   */
  grep?: string;
  /**
   * Invert the selection specified by the 'grep' option.
   */
  invertGrep?: boolean;
  /**
   * Override specs in the protractor config.
   */
  specs?: string[];
  /**
   * Override suite in the protractor config.
   */
  suite?: string;
  /**
   * Try to update webdriver.
   */
  webdriverUpdate?: boolean;
  /**
   * The port to use to serve the application.
   */
  port?: number;
  /**
   * Host to listen on.
   */
  host?: string;
  /**
   * Base URL for protractor to connect to.
   */
  baseUrl?: string;
}
interface UniversalTarget {
  /**
   * List of static application assets.
   */
  assets?: (
    | {
        /**
         * Allow glob patterns to follow symlink directories. This allows subdirectories of the symlink to be searched.
         */
        followSymlinks?: boolean;
        /**
         * The pattern to match.
         */
        glob?: string;
        /**
         * The input directory path in which to apply 'glob'. Defaults to the project root.
         */
        input?: string;
        /**
         * An array of globs to ignore.
         */
        ignore?: string[];
        /**
         * Absolute path within the output.
         */
        output?: string;
      }
    | string
  )[];
  /**
   * The name of the main entry-point file.
   */
  main?: string;
  /**
   * The name of the TypeScript configuration file.
   */
  tsConfig?: string;
  /**
   * The stylesheet language to use for the application's inline component styles.
   */
  inlineStyleLanguage?: 'css' | 'less' | 'sass' | 'scss';
  /**
   * Options to pass to style preprocessors
   */
  stylePreprocessorOptions?: {
    /**
     * Paths to include. Paths will be resolved to workspace root.
     */
    includePaths?: string[];
  };
  /**
   * Enables optimization of the build output. Including minification of scripts and styles, tree-shaking and dead-code elimination. For more information, see https://angular.io/guide/workspace-config#optimization-configuration.
   */
  optimization?:
    | {
        /**
         * Enables optimization of the scripts output.
         */
        scripts?: boolean;
        /**
         * Enables optimization of the styles output.
         */
        styles?: boolean;
      }
    | boolean;
  /**
   * Replace compilation source files with other compilation source files in the build.
   */
  fileReplacements?: (
    | {
        src?: string;
        replaceWith?: string;
      }
    | {
        replace?: string;
        with?: string;
      }
  )[];
  /**
   * Path where output will be placed.
   */
  outputPath?: string;
  /**
   * The path where style resources will be placed, relative to outputPath.
   */
  resourcesOutputPath?: string;
  /**
   * Output source maps for scripts and styles. For more information, see https://angular.io/guide/workspace-config#source-map-configuration.
   */
  sourceMap?:
    | {
        /**
         * Output source maps for all scripts.
         */
        scripts?: boolean;
        /**
         * Output source maps for all styles.
         */
        styles?: boolean;
        /**
         * Output source maps used for error reporting tools.
         */
        hidden?: boolean;
        /**
         * Resolve vendor packages source maps.
         */
        vendor?: boolean;
      }
    | boolean;
  /**
   * URL where files will be deployed.
   */
  deployUrl?: string;
  /**
   * Generate a seperate bundle containing only vendor libraries. This option should only be used for development to reduce the incremental compilation time.
   */
  vendorChunk?: boolean;
  /**
   * Adds more details to output logging.
   */
  verbose?: boolean;
  /**
   * Log progress to the console while building.
   */
  progress?: boolean;
  /**
   * How to handle missing translations for i18n.
   */
  i18nMissingTranslation?: 'warning' | 'error' | 'ignore';
  /**
   * How to handle duplicate translations for i18n.
   */
  i18nDuplicateTranslation?: 'warning' | 'error' | 'ignore';
  /**
   * Translate the bundles in one or more locales.
   */
  localize?: boolean | [string, ...string[]];
  /**
   * Define the output filename cache-busting hashing mode.
   */
  outputHashing?: 'none' | 'all' | 'media' | 'bundles';
  /**
   * Delete the output path before building.
   */
  deleteOutputPath?: boolean;
  /**
   * Do not use the real path when resolving modules. If unset then will default to `true` if NodeJS option --preserve-symlinks is set.
   */
  preserveSymlinks?: boolean;
  /**
   * Extract all licenses in a separate file, in the case of production builds only.
   */
  extractLicenses?: boolean;
  /**
   * Enables advanced build optimizations.
   */
  buildOptimizer?: boolean;
  /**
   * Use file name for lazy loaded chunks.
   */
  namedChunks?: boolean;
  /**
   * Exclude the listed external dependencies from being bundled into the bundle. Instead, the created bundle relies on these dependencies to be available during runtime.
   */
  externalDependencies?: string[];
  /**
   * Generates a 'stats.json' file which can be analyzed using tools such as 'webpack-bundle-analyzer'.
   */
  statsJson?: boolean;
  /**
   * Run build when files change.
   */
  watch?: boolean;
  /**
   * Enable and define the file watching poll time period in milliseconds.
   */
  poll?: number;
}
/**
 * ng-packagr target options for Build Architect. Use to build library projects.
 */
interface NgPackagrTarget {
  /**
   * The file path for the ng-packagr configuration file, relative to the current workspace.
   */
  project?: string;
  /**
   * The full path for the TypeScript configuration file, relative to the current workspace.
   */
  tsConfig?: string;
  /**
   * Run build when files change.
   */
  watch?: boolean;
}
